version: '3'

services:
  cassandra:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=admin123
      - CASSANDRA_USER=admin
      - CASSANDRA_CLUSTER_NAME=cassandra
    volumes:
      - ./docker-data/cassandra-persistence:/bitnami
    ports:
      - "9042:9042"
