version: "3"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=my_cluster
      - node.name=my_node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=somethingsecret
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - SERVER_NAME=localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=somethingsecret


volumes:
  elasticsearch-data:
