version: '3.0'
services:
  mysql:
    command:
      --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    volumes:
      - ./docker-data/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
