version: '3.0'
services:
  postgres:
    image: kartoza/postgis
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/
