version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis/data:/data
    command: redis-server --requirepass ${PASSWORD} --appendonly yes
